export const ADD_TO_FAVOR_REQUEST = "ADD_TO_FAVOR_REQUEST";
export const ADD_TO_FAVOR_SUCCESS = "ADD_TO_FAVOR_SUCCESS";
export const ADD_TO_FAVOR_FAIL = "ADD_TO_FAVOR_FAIL";
export const ADD_TO_FAVOR_RESET = "ADD_TO_FAVOR_RESET";

export const GET_FAVOR_REQUEST = "GET_FAVOR_REQUEST";
export const GET_FAVOR_SUCCESS = "GET_FAVOR_SUCCESS";
export const GET_FAVOR_FAIL = "GET_FAVOR_FAIL";

export const DELETE_FAVOR_REQUEST = "DELETE_FAVOR_REQUEST";
export const DELETE_FAVOR_SUCCESS = "DELETE_FAVOR_SUCCESS";
export const DELETE_FAVOR_FAIL = "DELETE_FAVOR_FAIL";
export const DELETE_FAVOR_RESET = "DELETE_FAVOR_RESET";