export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_FAIL = 'POST_LIST_FAIL';

export const POST_CREATE_REQUEST = 'POST_LIST_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_CREATE_FAIL = 'POST_LIST_FAIL';
export const POST_CREATE_RESET = 'POST_CREATE_RESET';

export const POST_DETAIL_REQUEST = 'POST_DETAIL_REQUEST';
export const POST_DETAIL_SUCCESS = 'POST_DETAIL_SUCCESS';
export const POST_DETAIL_FAIL = 'POST_DETAIL_FAIL';

export const POST_APPROVE_REQUEST = 'POST_APPROVE_REQUEST';
export const POST_APPROVE_SUCCESS = 'POST_APPROVE_SUCCESS';
export const POST_APPROVE_FAIL = 'POST_APPROVE_FAIL';
export const POST_APPROVE_RESET = 'POST_APPROVE_RESET'

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL';
export const POST_UPDATE_RESET = 'POST_UPDATE_RESET';

export const POST_LIKE_REQUEST = 'POST_LIKE_REQUEST';
export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS';
export const POST_LIKE_FAIL = 'POST_LIKE_FAIL';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';
export const POST_DELETE_RESET = 'POST_DELETE_RESET';